### ISSUE TITLE
Kill objection processes

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/appstraction#24]
We're keeping track of the objection processes we start:

https://github.com/tweaselORG/appstraction/blob/6903babd6446b01af68a7880f02e8f31ce1d4338/src/android.ts#L133

However, we never do anything with those. We need to kill them when we are done with the particular app.

The problem is that we don't know when that is. Maybe this is more of a hot-glue concept (where we _do_ have a "stop app analysis" function)?

This problem would also disappear if we switched to a raw Frida script for the certificate pinning bypass (https://github.com/tweaselORG/meta/issues/16).

**Comment by zner0L** [comment]
How about we kill the objection process in `stopApp`? Since we start them in `startApp` that seems kinda intuitive.

**Comment by baltpeter** [comment]
I did consider that but I don't think it's a good solution considering the user may well never call `stopApp()`. And solving this only for some cases would make this quite unpredictable, which I don't like.
