### ISSUE TITLE
Add function to configure battery optimizations on Android

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/appstraction#34]
Needed for automatically controlling WireGuard (cf. https://github.com/tweaselORG/meta/issues/19).

**Comment by baltpeter** [comment]
One way to do that is using `dumpsys deviceidle whitelist` ([via](https://gist.github.com/androidneha/896ec6b08137ef75a95341550b9c60fc)):

* Disable background optimizations for an app (add it to the allowlist): `adb shell dumpsys deviceidle whitelist "+<app ID>"`
* Enable background optimizations for an app (remove it from the allowlist): `adb shell dumpsys deviceidle whitelist "-<app ID>"`
* Get status for an app (`true` means it is on the allowlist, i.e. battery optimizations are disabled; `false` means it is not on the allowlist, i.e. battery optimizations are enabled): `adb shell dumpsys deviceidle whitelist "=<app ID>"`

**Comment by baltpeter** [comment]
There are also the `RUN_IN_BACKGROUND` and `RUN_ANY_IN_BACKGROUND` permissions that can be set via `appops` ([via](https://developer.android.com/topic/performance/background-optimization)).

The state of that can be read using `adb shell cmd appops get <app ID> <permission ID>`. And according to the source:

* To simulate conditions where implicit broadcasts and background services are unavailable: `adb shell cmd appops set <app ID> RUN_IN_BACKGROUND ignore`
* To re-enable implicit broadcasts and background services: `adb shell cmd appops set <app ID> RUN_IN_BACKGROUND allow`

I'm not quite sure what these do yet, and especially what the difference between `RUN_IN_BACKGROUND` and `RUN_ANY_IN_BACKGROUND` is.

**Comment by baltpeter** [comment]
Ah okay, "battery optimizations" is actually a tristate rather than a boolean.

On Android 9, this was split into two options. There was a "background restriction" option that could either be set to "restricted" or "app can use battery in background" (default), and a separate "background optimization" option that could be "not optimizing battery use" or "optimizing battery use" (default):

![Screenshot_20230306-114931_Settings](https://user-images.githubusercontent.com/4048809/223090543-cbf2bbbd-cf0a-4254-8db7-845d7ad76b1a.png)

And if "background optimization" was set to "not optimizing battery use", the "background restriction" option was disabled.

On Android 13 (probably earlier than that, but that's what I tested with), these have been collapsed into a single "app battery usage" option that can be "unrestricted", "optimized", or "restricted":

![Screenshot_20230306-114826_Settings](https://user-images.githubusercontent.com/4048809/223090984-521f8fdd-6299-4efa-b1e6-b785494f09e4.png)

**Comment by baltpeter** [comment]
So, let's see what these options correspond to.

On Android 13:

* "Unrestricted":
	* `dumpsys deviceidle whitelist`: `true`
	* `appops get RUN_IN_BACKGROUND`: `No operations. Default mode: allow`
	* `appops get RUN_ANY_IN_BACKGROUND`: `allow`
* "Optimized":
	* `dumpsys deviceidle whitelist`: `false`
	* `appops get RUN_IN_BACKGROUND`: `No operations. Default mode: allow`
	* `appops get RUN_ANY_IN_BACKGROUND`: `allow`
* "Restricted":
	* `dumpsys deviceidle whitelist`: `false`
	* `appops get RUN_IN_BACKGROUND`: `No operations. Default mode: allow`
	* `appops get RUN_ANY_IN_BACKGROUND`: `ignore`

On Android 9:

* "Unrestricted":
	* `dumpsys deviceidle whitelist`: `true`
	* `appops get RUN_IN_BACKGROUND`: `No operations. Default mode: allow`
	* `appops get RUN_ANY_IN_BACKGROUND`: `allow`
* "Optimized":
	* `dumpsys deviceidle whitelist`: `false`
	* `appops get RUN_IN_BACKGROUND`: `No operations. Default mode: allow`
	* `appops get RUN_ANY_IN_BACKGROUND`: `No operations. Default mode: allow`
* "Restricted":
	* `dumpsys deviceidle whitelist`: `false`
	* `appops get RUN_IN_BACKGROUND`: `No operations. Default mode: allow`
	* `appops get RUN_ANY_IN_BACKGROUND`: `ignore`

**Comment by baltpeter** [comment]
Where does that leave us? Luckily, despite the UI changes, it seems like the underlying mechanism hasn't changed and we won't need to do things differently for different Android versions.

`RUN_IN_BACKGROUND` doesn't seem to be used (anymore?). According to https://appops.rikka.app/guide/technical/run_in_background/, `RUN_IN_BACKGROUND` was introduced in Android 7, and `RUN_ANY_IN_BACKGROUND` was introduced in Android 9 (presumably replacing the former?).

**Comment by scruel** [comment]
https://github.com/tweaselORG/appstraction/issues/34#issuecomment-1455938039
Won't work with MIUI/hyperOS
