### ISSUE TITLE
Android: Automatically install WireGuard app in `ensureDevice()` if necessary

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/appstraction#38]
For the upcoming WireGuard support in #27, the user currently needs to manually install and configure the WireGuard app beforehand.

Wouldn't it be nice if we could do that automatically for the user? Shouldn't be too hard, essentially:

* Download the latest APK to a tmp file.
* Install that.
* Write the config in `/data/data/com.wireguard.android/files/datastore/settings.preferences_pb` to allow remote control.

**Comment by baltpeter** [comment]
Since WireGuard [don't seem to distribute APKs themselves](https://www.wireguard.com/install/#android-play-store-f-droid), I'll download them from F-Droid.

Currently, the download link for the latest version is ([via](https://f-droid.org/en/packages/com.wireguard.android/)):

```
https://f-droid.org/repo/com.wireguard.android_492.apk
```

How do we find the correct version code (`492`) in the future? https://f-droid.org/en/docs/All_our_APIs/ has the answer, there's an API endpoint:

```
https://f-droid.org/api/v1/packages/com.wireguard.android
```

This returns:

```json
{
  "packageName": "com.wireguard.android",
  "suggestedVersionCode": 492,
  "packages": [
    {
      "versionName": "1.0.20220516",
      "versionCode": 492
    },
    {
      "versionName": "1.0.20211029",
      "versionCode": 491
    },
    {
      "versionName": "1.0.20210926",
      "versionCode": 490
    }
  ]
}
```

**Comment by baltpeter** [comment]
I didn't find a Node library for downloading files that I liked. But it seems like Android ships with `curl`, and downloading the APK directly to the device is more efficient anyway, so we'll do that.

**Comment by baltpeter** [comment]
One annoying detail I forgot: In order to write to `/data/data/com.wireguard.android/files/datastore/settings.preferences_pb`, we need root access. :/

I'll have to throw an error if the user calls `ensureDevice()` with `wireguard` but without `root` and if the WireGuard app isn't installed already.

**Comment by baltpeter** [comment]
Next problem: We need to set the `allow_remote_control_intents` option in the config. But the config is a binary Protobuf (see https://github.com/tweaselORG/meta/issues/19#issuecomment-1446740935).

And as far as I can tell, a config file is only created if the user actually changes something in the settings, not by default. So we can't modify an existing config file anyway.

Instead, we'll distribute a known-good config file with appstraction and just write that. How do we do that for a binary file? Easy: as a string. :D 

First: `adb pull /data/data/com.wireguard.android/files/datastore/settings.preferences_pb`

Then:

```ts
import { readFile } from 'fs/promises';

(async () => {
    const file = await readFile('settings.preferences_pb', 'utf-8');
    console.log(JSON.stringify(file));
})();
```

Produces:

```ts
"\n\u0015\n\u000frestore_on_boot\u0012\u0002\b\u0000\n\u0010\n\ndark_theme\u0012\u0002\b\u0000\n\u0016\n\u0010multiple_tunnels\u0012\u0002\b\u0000\n\"\n\u001callow_remote_control_intents\u0012\u0002\b\u0001"
```

**Comment by baltpeter** [comment]
Actually, not quite so easy, it seems… If I copy the `settings.preferences_pb` generated by the app itself to a fresh installation, it doesn't show any tunnels in the list and crashes when I try to access the settings.

**Comment by baltpeter** [comment]
Oh, the permissions are probably the problem. Of course.

Config generated by the app:

```
ocean:/data/data/com.wireguard.android # ls -lZ files/datastore/                                                                                
total 4
-rw------- 1 u0_a168 u0_a168 u:object_r:app_data_file:s0:c168,c256,c512,c768  101 2023-03-06 20:54 settings.preferences_pb
```

Config put there by me:

```
ocean:/data/data/com.wireguard.android # ls -lZ files/datastore/                                                                                
total 4
-rw-rw-rw- 1 root root u:object_r:app_data_file:s0:c160,c256,c512,c768  101 2023-03-06 20:49 settings.preferences_pb
```

**Comment by baltpeter** [comment]
Maybe we need to match the permissions exactly? Let's see…

```
ocean:/ # ls -lZa /data/data/com.wireguard.android                                                                                              
total 32
drwx------   5 u0_a170 u0_a170       u:object_r:app_data_file:s0:c170,c256,c512,c768   3464 2023-03-07 12:13 .
drwxrwx--x 204 system  system        u:object_r:system_data_file:s0:c512,c768         24576 2023-03-07 12:13 ..
drwxrws--x   2 u0_a170 u0_a170_cache u:object_r:app_data_file:s0:c170,c256,c512,c768   3464 2023-03-07 12:13 cache
drwxrws--x   2 u0_a170 u0_a170_cache u:object_r:app_data_file:s0:c170,c256,c512,c768   3464 2023-03-07 12:13 code_cache
drwxrwx--x   3 u0_a170 u0_a170       u:object_r:app_data_file:s0:c170,c256,c512,c768   3464 2023-03-07 12:13 files
ocean:/ # ls -lZa /data/data/com.wireguard.android/files/                                                                                       
total 9
drwxrwx--x 3 u0_a170 u0_a170 u:object_r:app_data_file:s0:c170,c256,c512,c768  3464 2023-03-07 12:13 .
drwx------ 5 u0_a170 u0_a170 u:object_r:app_data_file:s0:c170,c256,c512,c768  3464 2023-03-07 12:13 ..
drwx------ 2 u0_a170 u0_a170 u:object_r:app_data_file:s0:c170,c256,c512,c768  3464 2023-03-07 12:13 datastore
ocean:/ # ls -lZa /data/data/com.wireguard.android/files/datastore/                                                                             
total 10
drwx------ 2 u0_a170 u0_a170 u:object_r:app_data_file:s0:c170,c256,c512,c768  3464 2023-03-07 12:13 .
drwxrwx--x 3 u0_a170 u0_a170 u:object_r:app_data_file:s0:c170,c256,c512,c768  3464 2023-03-07 12:13 ..
-rw------- 1 u0_a170 u0_a170 u:object_r:app_data_file:s0:c170,c256,c512,c768   101 2023-03-07 12:13 settings.preferences_pb
```

**Comment by baltpeter** [comment]
I'm still getting the problem even if I:

* Install the app.
* Start it and change a setting to make it create the directories and config file itself.
* Stop the app.
* Overwrite the file with an exact copy using `adb push`.
* Recreate the exact same permissions.

What am I missing? Is there some other integrity mechanism that I'm triggering? But how would that work if I put the exact same file back?

**Comment by baltpeter** [comment]
Nevermind, I just wasn't paying enough attention. The SELinux context was slightly different. 

This didn't work:

```
ocean:/ # ls -lZa /data/data/com.wireguard.android/files/datastore/                                                                             
total 10
drwx------ 2 u0_a171 u0_a171 u:object_r:app_data_file:s0:c171,c256,c512,c768  3464 2023-03-07 12:21 .
drwxrwx--x 3 u0_a171 u0_a171 u:object_r:app_data_file:s0:c171,c256,c512,c768  3464 2023-03-07 12:20 ..
-rw------- 1 u0_a171 u0_a171 u:object_r:app_data_file:s0:c160,c256,c512,c768   101 2023-03-07 12:21 settings.preferences_pb
```

But if I set the context to `u:object_r:app_data_file:s0:c171,c256,c512,c768` (the `c171` has to match the user (`a171`) using `chcon u:object_r:app_data_file:s0:c171,c256,c512,c768 /data/data/com.wireguard.android/files/datastore/settings.preferences_pb`, it does work.

But [`chcon` is only for temporary changes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-security-enhanced_linux-working_with_selinux-selinux_contexts_labeling_files#sect-Security-Enhanced_Linux-SELinux_Contexts_Labeling_Files-Temporary_Changes_chcon).

**Comment by baltpeter** [comment]
I'm making a bit of process. This works to override an existing config file (you need to specify the correct user):

```sh
su u0_a172 -c "echo -n '\n\u0015\n\u000frestore_on_boot\u0012\u0002\b\u0000\n\u0010\n\ndark_theme\u0012\u0002\b\u0000\n\u0016\n\u0010multiple_tunnels\u0012\u0002\b\u0000\n\"\n\u001callow_remote_control_intents\u0012\u0002\b\u0001' > /data/data/com.wireguard.android/files/datastore/settings.preferences_pb"
```

**Comment by baltpeter** [comment]
Oh yes! I've managed to make this work after a fresh installation without ever starting the app  (again, the user needs to be replaced with the correct value):

```sh
su u0_a176 -c "mkdir -p /data/data/com.wireguard.android/files/datastore"
su u0_a176 -c "echo -n '\n\u0015\n\u000frestore_on_boot\u0012\u0002\b\u0000\n\u0010\n\ndark_theme\u0012\u0002\b\u0000\n\u0016\n\u0010multiple_tunnels\u0012\u0002\b\u0000\n\"\n\u001callow_remote_control_intents\u0012\u0002\b\u0001' > /data/data/com.wireguard.android/files/datastore/settings.preferences_pb" 
```

This produces a simpler SELinux context, but it does work:

```
ocean:/data/local/tmp # ls -lZa /data/data/com.wireguard.android/files/datastore/                                                               
total 10
drwxr-xr-x 2 u0_a176 u0_a176 u:object_r:app_data_file:s0  3464 2023-03-07 12:55 .
drwxr-xr-x 3 u0_a176 u0_a176 u:object_r:app_data_file:s0  3464 2023-03-07 12:55 ..
-rw-r--r-- 1 u0_a176 u0_a176 u:object_r:app_data_file:s0   101 2023-03-07 12:55 settings.preferences_pb
```

**Comment by baltpeter** [comment]
Now I'm running into problems trying to run that with execa. *sigh*

> The argument 'args[4]' must be a string without null bytes.

**Comment by baltpeter** [comment]
Conveniently, Android ships with `base64`.

**Comment by baltpeter** [comment]
It works. \o/

**Comment by baltpeter** [comment]
One more problem: Even though we can now install the app and write the config, our `setProxy()` function doesn't work afterwards.

If I try to start the tunnel manually, I get a VPN connection request popup by Android:

![Screenshot_20230307-135058_VpnDialogs](https://user-images.githubusercontent.com/4048809/223427216-75b81905-8528-45f2-aee1-9deefaf05ed6.png)

**Comment by baltpeter** [comment]
[Reddit](https://www.reddit.com/r/Windows11/comments/t2nktc/comment/hyo2sua/) has the solution. The VPN permission can be granted programmatically like this:

```sh
appops set <app ID> ACTIVATE_VPN allow
```

**Comment by baltpeter** [comment]
But now enabling the tunnel fails with: "Error bringing up tunnel: open failed: EACCES (Permission denied)".

Probably because it is owned by root?

```
ocean:/data/local/tmp # ls -lZa /data/data/com.wireguard.android/files/                                                                         
total 17
drwxr-xr-x 3 u0_a187 u0_a187 u:object_r:app_data_file:s0                      3464 2023-03-07 14:05 .
drwx------ 5 u0_a187 u0_a187 u:object_r:app_data_file:s0:c187,c256,c512,c768  3464 2023-03-07 14:03 ..
-rw-rw-rw- 1 root    root    u:object_r:app_data_file:s0:c160,c256,c512,c768   224 2023-03-07 14:05 appstraction.conf
drwxr-xr-x 2 u0_a187 u0_a187 u:object_r:app_data_file:s0                      3464 2023-03-07 14:04 datastore
```

But the file is world-readable (and -writable) and this did work before… Huh. Anyway, I'll try the same `su` trick as for the config. That's cleaner anyway.

**Comment by baltpeter** [comment]
Yep, with that it finally seems to work and we've gotten rid of one temporary file. \o/

**Comment by zner0L** [comment]
This all sound great! It would be nice if we added an option to take a snapshot after the install so that we can come back to that in cyanoacrylate, if we are doing lots of analyses this would save some time!

**Comment by zner0L** [comment]
On my emulator (API level 33) , I am unable to configure wireguard, because `su <wireguard user> -c "mkdir -p /data/data/com.wireguard.android/files/datastore" ` fails with `su: failed to exec -c: Permission denied`. This happens for all commands I run using `su -c`. If I just `su` into the user and then run the command, I have no problems.

**Comment by zner0L** [comment]
I think the problem is that there are no login shells set for any user on the emu, `/etc/passwd` is completely empty. If I instead run `su <wireguard user> /bin/sh -c "mkdir -p /data/data/com.wireguard.android/files/datastore" ` it just works.
