### ISSUE TITLE
Bail sooner in `ensureDevice()` on Android if no device is found

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/appstraction#57]
Currently, if you forgot to connect your device or start the emulator, `ensureDevice()` will wait 25 seconds before telling you. That is quite annoying.

The long delay is because we now wait for the emulator to start. That is fine. But we don't need to wait that long if there is no device anyway.

**Comment by baltpeter** [comment]
The behaviour is also inconsistent with iOS where we immediately fail when no device is found. In https://github.com/tweaselORG/cli/pull/11, I implemented the "wait for device" step by calling the internal `awaitAdb()` but only on Android:

https://github.com/tweaselORG/cli/pull/11/files#diff-99e877e9d59c51d79916d9842750f9e794be5a8215d4910896d48c10a0bdc155R252-R261

Maybe we should just have a separate `waitForDevice()` function and have `ensureDevice()` expect the device to already be ready?

**Comment by zner0L** [comment]
Well, it actually never tells you because `adb wait-for-device` will keep running forever if you don’t connect a device, which is why I filed the other issue, but I guess they are similar enough.

**Comment by zner0L** [comment]
Well, in iOS we don’t need to wait for an emulator…

**Comment by zner0L** [comment]
Isn’t the whole point of `ensureDevice` to ensure a device is present? But as I suggested in #76, we could fail immediately for `runTarget: device`.

**Comment by baltpeter** [comment]
> Well, in iOS we don’t need to wait for an emulator…

But that's not wait `waitForAdb()` does either. It waits for the device to be booted. That could also be a physical device. The emulator was just our initial need for this functionality.

Otherwise, I would have pushed the code to CA or even CLI. But I do also see potential uses for it as a primitive in appstraction.

**Comment by baltpeter** [comment]
> Isn’t the whole point of `ensureDevice` to ensure a device is present? But as I suggested in #76, we could fail immediately for `runTarget: device`.

Yes. But ensure !== await. Before #51, we were just checking once instead of waiting:

https://github.com/tweaselORG/appstraction/pull/51/files#diff-34632e78f038aee01b56eebd9e73483544c8127003466eb473ca92f91cad74f1L49-L52

To me, that is what `ensureDevice()` is supposed to do.

**Comment by zner0L** [comment]
Well, checking without waiting often failed for emulators. How about a `waitForDevice` flag in `ensureDevice`?

**Comment by baltpeter** [comment]
You could essentially achieve the same thing by calling `waitForDevice()` before `ensureDevice()`.

My main reason for wanting these to be separate functions is for CLI. https://github.com/tweaselORG/cli/issues/8 is a very valid request but hard to implement since `ensureDevice()` is a huge intransparent blob that does a million things and you have no way of knowing what it's doing at any given time. With a separate `waitForDevice()` we could at least have the (probably) longest part of this (and the one that will hang forever/a long time if no device is connected) separate.

And if you want to have `ensureDevice()` be the one-stop-shop for getting the device ready, I wouldn't mind an additional flag that then calls `waitForDevice()`.

**Comment by zner0L** [comment]
Ok, I’ll implement it like this.

**Comment by zner0L** [comment]
Actually, now that I work on this, I think adding a flag doesn’t make sense. You are right (again) :D
